{% set name = "psyplot-gui" %}
{% set version = "1.5.0" %}
{% set sha256 = "005970958a636cb6818a984fd9c7e4849c14e7e363d87a6479f4ae5ca82c5565" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - versioneer
    - tomli
  run:
    - python
    - {{ pin_compatible('psyplot', max_pin='x.x', lower_bound='1.5.0') }}
    - qtconsole
    - pyqtwebengine
    - fasteners
    - numpy >=1.14  # [win]
    - sphinx
    - sphinx_rtd_theme

test:
  commands:
    - psyplot --help
  imports:
    - psyplot_gui
    - psyplot_gui.compat
    - psyplot_gui.config
    - psyplot_gui.sphinx_supp

app:
  entry: psyplot
  icon: logo.png
  summary: Psyplot visualization software
  type: desk

about:
  home: https://codebase.helmholtz.cloud/psyplot/psyplot-gui
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSES/
  summary: Graphical user interface for the psyplot package

  description: |
    This package provides a graphical user interface to interact with the
    psyplot framework.
  doc_url: https://psyplot.github.io/psyplot-gui
  dev_url: https://codebase.helmholtz.cloud/psyplot/psyplot-gui

extra:
  recipe-maintainers:
    - Chilipp
