appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: T0P1ULH2MQEPPRmkJ+MEjKpLQibfFf3elEBn712vqPz6rAgzPEMJ1szR/bQlr6FvtdxBTqFOO08b0/Ucfew4AqdS9h1sY8Stq85on6j7cljss52g10R4yhhXo3/J1GEH4btW6NUDon9ol3KvdKXDOt2Si8Df1LMU0HV3M8CcS2EZt6mcqzQKws0RxP7SV5SZGgwbTQ03M/jzvKgrQrOrdCYT6KlDss7csXBxiDeBUdk23X79L8j+aLDmfWAengrbtLPohVMStJp5uGjU8fY+bjVobTpPym/dN+SEBDMOX9KLkhQYaMHL4p2npIN4ookoKiYH+BxBhDTfW898wFJ0THtrbEgpp7PU4PqbAn8HSKpOWvnrfZzZk6ICPWOOiVp0JIRBjD649jsjJXSKewv+dV9iVP3zjvy9mfpfPOEUuAQqlCriMJT2ezDgoqEx0QRJaSn9o3nFy8eU/0FDBXhdHEut3Se9HuRLeZcRGfhrKP4NM+zBjHKREU76jqsMxZjROj4TFru0ey65Lqfgw4KNcZp4Bm5e+J75KIu5L3VoIX/N2MESB2z/+5tK3GnMSMaAmNdhWTFZAndOLRicJJQ0pL8bx92HT0rXX7EpbrSdwKgITK7kwjYbFh03GxW8yvabBs2m0PY8SrBtmDWl7trqqaf51PGlwmfI19olomkYnRY=}
provider:
  win: azure
conda_forge_output_validation: true
